name: CI/CD Pipeline with TLS

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout repo
    - name: Checkout repo
      uses: actions/checkout@v4

    # 2️⃣ Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # 3️⃣ Build Docker image
    - name: Build Docker image
      run: |
        docker build -t wisecow:ci .

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "18"

    # 4️⃣ Set up Kind (Kubernetes in CI)
    - name: Set up Kind
      uses: engineerd/setup-kind@v0.6.2
      with:
        version: v0.24.0

    # 5️⃣ Load image into Kind
    - name: Load image into Kind
      run: kind load docker-image wisecow:ci

    # 6️⃣ Set up kubectl
    - name: Set up kubectl
      uses: azure/setup-kubectl@v4

    # 7️⃣ Create TLS Secret (self-signed)
    - name: Create TLS Secret
      run: |
        openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
          -keyout tls.key -out tls.crt \
          -subj "/CN=wisecow.default.svc.cluster.local/O=Wisecow"
        kubectl create secret tls wisecow-tls --key tls.key --cert tls.crt

    # 8️⃣ Deploy Kubernetes manifests
    - name: Deploy to Kind cluster
      run: |
        kubectl apply -f k8s/wisecow-service.yaml
        kubectl apply -f k8s/wisecow-deployment.yaml
        kubectl apply -f k8s/wisecow-ingress.yaml
        kubectl rollout status deployment/wisecow-deployment --timeout=120s


    # 9️⃣ Smoke test over HTTPS
    - name: Smoke test (HTTPS)
      run: |
        kubectl run curlpod --image=radial/busyboxplus:curl --restart=Never --command -- sleep 30s
        kubectl exec curlpod -- curl -k https://wisecow.default.svc.cluster.local/
